### ISSUE TITLE
Create project outline

### ISSUE THREAD

**Issue by larsjohan** [larsjohan/MCLore#1]
# TODO:
- [X] Create maven-project
- [X] Add spigot dependencies
- [x] Create folderstructure
- [x] Configure JUnit
- [x] Configure SonarQube-properties for static analysis of code
- [x] Configure test-reporting (Surefire/jacoco)
