### ISSUE TITLE
Make plugin loadable by a server

### ISSUE THREAD

**Issue by larsjohan** [larsjohan/MCLore#2]
# TODO
- [x] Remove Test-code from initial setup
- [x] Create the basic skeleton to make the plugin loadable by a server.
- [ ] Define basic information in plugin.yaml
